### ISSUE TITLE
Streaks on image

### ISSUE THREAD

**Issue by nuges01** [duguyue100/pyaer#10] opened 2019-02-02 06:14 UTC
![streaks](https://user-images.githubusercontent.com/9575270/52160632-7f518480-2687-11e9-92cd-ff6b1e29c2fe.png)
![streaks2](https://user-images.githubusercontent.com/9575270/52160634-81b3de80-2687-11e9-8cf4-b6bcb0fd3187.png)

Do you know what could be the cause of the streaks that are showing up in the images above? I'm not observing it on the jAER display.

Thanks!

**Comment by duguyue100** [comment] 2019-02-02 07:54
Mostly this streak is due to the bias issue. I think there are more bias values introduced for the latest version of DAVIS 346 while the program you are running uses the bias values in DAVIS 346B (an older model).

I will provide a fix as soon as I get the new camera myself.

Yuhuang.

**Comment by duguyue100** [comment] 2019-02-07 11:31
![](https://github.trello.services/images/mini-trello-icon.png) [fix the color mode for the new camera](https://trello.com/c/QopIm3Z3/424-fix-the-color-mode-for-the-new-camera)

**Comment by nuges01** [comment] 2019-02-08 15:23
Awesome! Thanks!

**Comment by duguyue100** [comment] 2019-02-08 18:52
@nuges01 I've been working on a fix today since I just got the camera.

To answer your question:

1. yes, your fix in issue #9 is indeed on the right track, however, you don't need to change it to RGB image again since `libcaer` in default outputs RGB frame events, the only reason that it seems a BGR image is because you are using OpenCV to display the image. I noticed this when I use my own renderer that is independent of the OpenCV. (just in case you are interested, you can find the code here: https://github.com/duguyue100/pyaer-demo/blob/master/demos/davis346_demo.py)

2. The streaks on the image is indeed an issue, I wasn't able to solve it now, it seems that `libcaer` has a small problem on putting a frame together. I will file an issue on `libcaer` team so that they can take a look.

I will release this version so you can have a more efficient frame generation and keep this issue open until I can solve it.

Yuhuang.

**Comment by tobidelbruck** [comment] 2019-02-12 07:53
I don't know the cause of these streaks. You say they don't show up when running with jAER?  Then it must be some biases, which include not only currents but also video timing.  I would have to have a camera with this problem to debug it.

**Comment by duguyue100** [comment] 2019-02-12 11:49
@nuges01 @tobidelbruck , this is indeed a bias issue, I've updated the bias value for DAVIS 346, you can check here: https://github.com/duguyue100/pyaer/blob/davis346-examine-bias/scripts/configs/davis346_config.json

The key is `ADC_RefHigh_volt` and `ADC_RefHigh_curr` I believe.

I will close this issue and update a new release.

Special thanks to @tobidelbruck

**Closed by duguyue100** 2019-02-12 11:49 UTC
